### ISSUE TITLE
Bugs in (srfi :126 r6rs-hashtables)

### ISSUE THREAD

**Issue by jessymilare** [arcfide/chez-srfi#14]
There are some bugs in (srfi :126 r6rs-hashtables). According to spec:

    - make-hashtable must always accept #f as hash procedure when equiv is eq? or eqv?;
    - make-hashtable must always accept a pair of hash procedures or a single procedure;
    - weakness can be a lot of values, and Chess Scheme accepts any one of them, but always produces weak-key hashtables. Chez Scheme should signal an error if weakness is one of the unsupported values (weak-value etc);

I've corrected those mistakes and did some optimizations in my own repo (last commit)

**Comment by jessymilare** [comment]
Here is a patch from my repo.
[0001-Corrected-bugs-and-optimized-srfi-126-r6rs-hashtable.txt](https://github.com/arcfide/chez-srfi/files/2577590/0001-Corrected-bugs-and-optimized-srfi-126-r6rs-hashtable.txt)

**Comment by arcfide** [comment]
Thanks for this. I have a few questions. Firstly, it would be vastly easier for me if you could submit this as a pull request on GitHub instead of a patch file. Secondly, it looks like most of the stuff that you're putting in the non-Chez Scheme files is portable, but I wanted to double check this, because I see a lot of new things thrown in, and I haven't had the time to go through each of them.

**Comment by jessymilare** [comment]
Ok! I created a pull request. I'll test the code with other implementations and then I tell you the results. I've added a test file with code from SRFI page, you can run the tests yourself if you like.

**Comment by arcfide** [comment]
Thanks for the pull request. I'm going to close this comment and follow up with things on the pull request. I believe my main concern at this point is just making sure that it doesn't break any of the existing implementations, since people have begun using this repository for more than just Chez Scheme now. 

I also appreciate the leg work you are doing on this. I admit that I'm mostly a moderator of patches on this repository at this point. :-)
