### ISSUE TITLE
Importing partial libraries

### ISSUE THREAD

**Issue by gwatt** [arcfide/chez-srfi#4]
Importing partial libraries from outside repo fails.
Setup:
* Checkout this repository into a directory `srfi` (Absolute path `~/chezlib/srfi`)
* Have `~/chezlib` in the CHEZSCHEMELIBDIRS
* Be anywhere outside of `~/chezlib/srfi`, like `~/`
* Try to import `(srfi :1 lists)`
This error results:
```
(import (srfi :1 lists))
Exception in include/resolve: cannot find file in search paths with irritants ("%3a1/srfi-1-reference.scm" ("~/chezlib/srfi/:1" "~/chezlib/srfi/:1" "."))
```
If you run scheme from within `~/chezlib/srfi` then the import works as desired.

**Comment by arcfide** [comment]
Thanks for the report. I'm trying to see if I can replicate this over here, but it might take some time.

**Comment by arcfide** [comment]
Okay, I took a look at this more closely and I've reverted my previous patch. The problem here isn't with the code, but you have not set up your environment to work correctly. You need to make sure that your `source-directories` parameter has the parent directory for your `srfi` checkout before the `include/resolve` syntax will work correctly.  So you need to make sure that you set up `library-directories` and `source-directories` correctly. Good luck!

**Comment by arcfide** [comment]
Jason Hemann suggests that most people will want to be able to do this automatically. So, if you want to launch arbitrary commands automatically, you can create a custom boot file to launch your Scheme code before you start. See the instructions in the Chez Scheme User's Guide on Building and Running Applications for more information. There is an environment variable to set the library directories parameter, and I think there is also an environment variable you can set for source-directories, but I can't seem to find it at the moment, so if you want you can use the boot files method, as it is the most flexible, though also the most work.
