### ISSUE TITLE
Outdated leap second table in SRFI-19

### ISSUE THREAD

**Issue by weinholt** [arcfide/chez-srfi#43]
The `tm:leap-second-table` list in srfi-19.scm is missing the leap seconds from 2012, 2015 and 2017 and should be updated.

This will be a perennial problem and I'm thinking about different solutions. Here are three ways to solve it:

1. Keep updating srfi-19.scm with new leap seconds. Anyone using an old srfi-19.scm will be using old values and their TAI times will be out of sync with everyone else. Someone should be subscribed to IERS Bulletin C to learn about new leap seconds.
2. Use the leap second database from the operating system. Debian ships `/usr/share/zoneinfo/leap-seconds.list` and I'm sure other systems have a copy of the same data somewhere.
3. Use an operating system interface that already returns TAI time, like clock_gettime(2) with `CLOCK_TAI`.

So with this issue I'd like to note that there is a problem and see if anyone has an opinion on what's the best solution.

**Comment by arcfide** [comment]
Normally, if it were just one implementation, I'd be in favor of using a known operating system call to get this information. However, with multiple implementations, maybe that isn't the best course of action? 

-- 
Aaron W. Hsu | arcfide@sacrideo.us | http://www.sacrideo.us

**Comment by lassik** [comment]
Leap seconds are added pretty sparsely nowadays: only three leap seconds in the last decade, last one was in 2016. So updating the hard-coded tables in Scheme codebases ought to be a good-enough first pass.

As a long-term solution, +1 for system call. As a fallback, use hard-coded table or read a well-known file like @weinholt suggests.

A while ago, Windows added a feature whereby its clock can display :60 when a leap second occurs. This must mean they also added a system call where one can get requisite information, and unless I misthought something, they have to store a leap second table in the kernel. Hopefully they have a syscall to read that table into userland, but not sure.

**Comment by lassik** [comment]
For future Scheming, I'd like a simple SRFI with:

(leap-second-table) -> return a vector of known leap seconds as integers; each positive value is a positive leap second, each negative value is a negative leap second; the magnitude is the timestamp since 1970

(tai-now) and (utc-now) -> get the current time since 1970 in TAI and UTC. could be returned as seconds; nanoseconds pair/values or seconds.fractional_seconds inexact real or seconds integer.

(tai->utc timestamp table) and (utc->tai timestamp table) -> convert between tai and utc using the given leap second table.

**Comment by arcfide** [comment]
I wonder what the WG2 folks are doing regarding time? 

-- 
Aaron W. Hsu | arcfide@sacrideo.us | http://www.sacrideo.us

**Comment by lassik** [comment]
@johnwcowan has a plan for at least one new time SRFI since SRFI 19 had some kind of fundamental problem. I forget the details.

**Comment by arcfide** [comment]
Okay, well, I'll accept a patch to the timetable if someone would like to do that, as it sounds like a very simple fix. Anyone who wishes to subsume that with an operating system call can feel free to submit a PR for the operating system and I presume we will be able to incrementally add more OS support over time. 

-- 
Aaron W. Hsu | arcfide@sacrideo.us | http://www.sacrideo.us

**Comment by johnwcowan** [comment]
My current design is at <https://github.com/johnwcowan/r7rs-work/blob/master/TimeAdvancedCowan.md>.  It is both more comprehensive than SRFI 19 (it handles time folds, for example) and less so (it does not make much sense to convert monotonic time to hours, minutes, and seconds, much less a calendar date, since the epoch is unknown).  It does not include anything about formatting.
